### ISSUE TITLE
my127/my127 package should auto-update

### ISSUE THREAD

**Issue by dantleech** [my127/workspace#102]
Workspace depends on the https://packagist.org/packages/my127/my127 package, but it is not auto-updated and so we currently bypass Packagist and reference it directly in `composer.json`

We should either:

- Enable auto-update

or possibly:

- Make that library part of `workspace`

See https://github.com/my127/php-library/issues/4

**Comment by g-foster2020** [comment]
No longer relevant as packages have been moved into workspace repo.
