### ISSUE TITLE
Call to `clone` on nullable value

### ISSUE THREAD

**Issue by dantleech** [my127/workspace#106]
```
ws helm kubeval --cleanup qa
PHP Fatal error:  Uncaught Error: __clone method called on non-object in phar:///usr/local/bin/ws/vendor/my127/my127/src/Console/src/Application/Event/InvalidUsageEvent.php:21
```

This bug is "upstream" in the `my127` library:

```
class InvalidUsageEvent extends Event
{
    private $input;

    public function __construct($args, OptionDefinitionCollection $options)
    {
        $this->input = (new InputSequenceFactory())->createFrom($args, $options);
    }

    public function getInputSequence(): InputSequence
    {
        return clone $this->input;
    }
}
```

`createFrom` can return NULL if a definition doesn't exist,

**Comment by kierenevans** [comment]
Is this fixed by https://github.com/my127/workspace/pull/89 ?

**Comment by dantleech** [comment]
No, looks like it's still possible: https://github.com/my127/php-library/blob/master/src/Console/src/Usage/Parser/InputSequenceFactory.php#L61

But maybe it fixes this specific instance?

**Comment by dantleech** [comment]
The PR fixes this issue, but the type still indicates that the return type is  `nullable`.

One safe way to fix this is to add another method rather than passing a flag.

**Comment by g-foster2020** [comment]
Closed specific issue as resolved by PR.
