### ISSUE TITLE
Workspace downloads latest version if it does not see a full semver reference

### ISSUE THREAD

**Issue by jameshalsall** [my127/workspace#109]
If you define the following in your `workspace.yml`:

```harness: foo:v0.13```

When you run `ws install` (or `ws harness download`) it just pulls down the latest version of the harness. Workspace should either:

1. Error, and tell the user that the version was not found; or better yet
2. Download the latest `0.13.x` release

**Comment by g-foster2020** [comment]
This has been resolved since the bug was raised.
