### ISSUE TITLE
Workspace should send a non-zero exit code when a command isn't matched

### ISSUE THREAD

**Issue by andytson-inviqa** [my127/workspace#36]
For instance, if workspace is unable to find a workspace.yml and is executing `ws install`, it prints out the usage and returns a 0 for its exit code.

A CI job would see this as a pass. It should be an error.

**Comment by dantleech** [comment]
See also https://github.com/my127/workspace/issues/62

**Comment by jameshalsall** [comment]
As raised by @dantleech in #62:

> Ideally the following would be good:

> ```
> $ ws global service proxy foobar
> Command "foobar" is not available on service "proxy", available commands "start", "stop", "restart"
> ```
