### ISSUE TITLE
Executing a ws command that does not exist should return a non-zero exit code

### ISSUE THREAD

**Issue by jameshalsall** [my127/workspace#45]
If I execute `ws foo` and no `foo` command is defined in the current workspace, then I expect a non-zero exit code to indicate that it was not successful. Printing the commands that are available, as it currently does, is helpful, but the exit code should be non-zero I think to indicate that something went wrong.

**Comment by andytson-inviqa** [comment]
duplicate of #36, sorry

**Comment by jameshalsall** [comment]
Oops, somehow I missed that looking in the issues list
