### ISSUE TITLE
`ws global service` should list available global services

### ISSUE THREAD

**Issue by kierenevans** [my127/workspace#61]
Current output:
```
ws global service

Usage:
  ws global service <name> <action> [options]


Global Options:
  -h, --help    Show help message
```

Would love to see:
```
ws global service

Sub Commands:
   logger
   mail
   proxy

Global Options:
  -h, --help    Show help message
```

based on `home/bin/ws.service` in this repository

**Comment by NoDiskInDriveA** [comment]
Like so? https://github.com/NoDiskInDriveA/workspace/tree/hardcode-global-services - this would be hardcoded but otherwise I think it would need to be a build step that creates `global.yml` because of the way my127 works right now.
